### ISSUE TITLE
[FEATURE]: Transactions récurrentes 

### ISSUE THREAD

**Issue by Natchii59** [Natchii59/ozepi#10]
### Description

Le but est de créer des dépenses récurrentes (ex: pour des loyers, etc).
Il faudra donc créer un autre model `RecurringTransaction` (`recurring_transaction` en base de données).
On aura comme propriété:
- amount
- type (`INCOME` ou `EXPENSE` via un enum)
- frequency (`DAILY`, `WEEKLY`, `MONTHLY`, `YEARLY` via un enum)
- dayOfWeek (0 pour dimanche et 6 pour samedi, uniquement pour hebdo)
- dayOfMonth (1 à 31, uniquement pour les mensuels et annuelles)
- month (1 à 12, uniquement pour les annuelles)

Il faudra faire des vérifications que les champs requis en fonction de la fréquence, sois envoyé lors de la requête (dto).
Il faudra également implémenter un cron-job qui passe tous les jours (à 00h), qui créé des transactions en fonction de la fréquence/période etc.
 Les transactions récurrentes peuvent être modifiées et supprimées. Elles peuvent uniquement être gérer, et c'est grâce à elles que les vraies transactions seront créées.

### Priorité

Basse

**Comment by Natchii59** [comment]
Il serait bien d'ajouter une partie dans la documentation pour lister tous les cron-jobs qui tournent.

**Comment by Natchii59** [comment]
En attente de l'issue #7

**Comment by Code-Barru** [comment]
Y'a aussi la propriété `wallet` qui est un wallet_id
