### ISSUE TITLE
[FEATURE]: CRUD wallets

### ISSUE THREAD

**Issue by Natchii59** [Natchii59/ozepi#6]
### Description

Le but est de pouvoir créer et gérer ses wallets.
Un wallet aura comme propriété un nom, une devise (EUR, US, etc). Un `user` doit pouvoir avoir plusieurs `wallet`.

L'utilisateur connecté doit pouvoir accès uniquement à ses wallets. Il y aura donc un système de pagination sur les wallets, un champ `totalCount` et `nodes` qui seront à disposition pour les paginations. Il seront créés via des via des `ResolveField`.

### Priorité

Moyenne

**Comment by Code-Barru** [comment]
## Correction

On met une valeur appelée `currentValue` en `readonly` qui se mettra à jour à chaque transactions.

**Comment by Natchii59** [comment]
La valeur `currentValue` sur le model `wallet` sera mis à jour uniquement sur le service des transactions. Il ne sera donc pas possible de mettre à jour cette valeur manuellement sans transaction.
Lors de la création du wallet, il sera aussi demandé la valeur de base du wallet (required).

**Comment by Code-Barru** [comment]
Ajouter également un booléen `hasFutureTransaction` pour filter leur cronjob.

**Comment by Natchii59** [comment]
En attente de l'issue #3

**Comment by Natchii59** [comment]
Cette issue permettra à @Code-Barru et @ColleryCorentin de se former sur Nestjs et GraphQL.
